// -----------------------------------------------------------------------------
// scripts/make-qr.mjs
//
// Bake the share sheet's QR code into public/qr-fieldmaps.svg.
//
// The code points at the site root and nothing else, so it is the same square
// forever — generating it on the device every time the share sheet opens would be
// work done repeatedly for a constant. Like scripts/fetch-osm.mjs, this is a
// one-off: run it, commit the output, and the app just ships an <img>.
//
// Run:  node scripts/make-qr.mjs
//
// Unlike fetch-osm.mjs this needs no network — the encoder is right here. It is
// deliberately narrow: byte mode, error correction level M, versions 1 to 6. The
// URL is 25 bytes, which lands in version 2. Stopping at 6 is what keeps it short;
// version 7 is where symbols start carrying a separately-encoded version number.
// -----------------------------------------------------------------------------

import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

/** What the code resolves to when scanned. */
const URL_TO_ENCODE = "https://www.fieldmaps.app";

/** Level M, as the two bits that go into the format information. */
const ECC_LEVEL_M = 0b00;

/** Per version: total codewords, ECC codewords per block, block count. Level M. */
const VERSIONS = [
	[0, 0, 0], // there is no version 0; this keeps the array 1-indexed
	[26, 10, 1],
	[44, 16, 1],
	[70, 26, 1],
	[100, 18, 2],
	[134, 24, 2],
	[172, 16, 4],
];

/** Row/column centres of the alignment patterns, per version. */
const ALIGNMENT = [[], [], [6, 18], [6, 22], [6, 26], [6, 30], [6, 34]];

// --- GF(256) ------------------------------------------------------------------
// The field the Reed-Solomon code lives in, generated by the primitive polynomial
// x^8 + x^4 + x^3 + x^2 + 1 that the QR spec fixes.

const EXP = new Uint8Array(256);
const LOG = new Uint8Array(256);
{
	let x = 1;
	for (let i = 0; i < 255; i++) {
		EXP[i] = x;
		LOG[x] = i;
		x <<= 1;
		if (x & 0x100) x ^= 0x11d;
	}
}

const gfMul = (a, b) => (a === 0 || b === 0 ? 0 : EXP[(LOG[a] + LOG[b]) % 255]);

/** The generator polynomial for `degree` ECC codewords, highest power first. */
function rsGenerator(degree) {
	let poly = [1];
	for (let i = 0; i < degree; i++) {
		const root = EXP[i];
		const next = new Array(poly.length + 1).fill(0);
		for (let j = 0; j < poly.length; j++) {
			next[j] ^= poly[j]; // x
			next[j + 1] ^= gfMul(poly[j], root); // a^i
		}
		poly = next;
	}
	return poly;
}

/** The ECC codewords for one block: the remainder of data / generator. */
function rsRemainder(data, gen) {
	const degree = gen.length - 1;
	const rem = new Array(degree).fill(0);
	for (const byte of data) {
		const factor = byte ^ rem[0];
		rem.shift();
		rem.push(0);
		for (let i = 0; i < degree; i++) rem[i] ^= gfMul(gen[i + 1], factor);
	}
	return rem;
}

// --- Bit stream ---------------------------------------------------------------

/** The smallest version that fits `byteLength` bytes, or 0 if nothing does. */
function pickVersion(byteLength) {
	for (let version = 1; version < VERSIONS.length; version++) {
		const [total, eccPerBlock, blocks] = VERSIONS[version];
		const data = total - eccPerBlock * blocks;
		// 4 bits of mode indicator + 8 bits of character count, then the payload.
		if (data * 8 - 12 >= byteLength * 8) return version;
	}
	return 0;
}

/** Mode indicator, length, payload, terminator, padding: the data codewords. */
function dataCodewords(bytes, version) {
	const [total, eccPerBlock, blocks] = VERSIONS[version];
	const capacity = total - eccPerBlock * blocks;

	const bits = [];
	const push = (value, length) => {
		for (let i = length - 1; i >= 0; i--) bits.push((value >>> i) & 1);
	};
	push(0b0100, 4); // byte mode
	push(bytes.length, 8); // versions 1-9 count characters in 8 bits
	for (const byte of bytes) push(byte, 8);

	// Terminator: up to four zero bits, fewer if the symbol is nearly full.
	push(0, Math.min(4, capacity * 8 - bits.length));
	while (bits.length % 8 !== 0) bits.push(0);

	const codewords = [];
	for (let i = 0; i < bits.length; i += 8) {
		let byte = 0;
		for (let j = 0; j < 8; j++) byte = (byte << 1) | bits[i + j];
		codewords.push(byte);
	}
	// The spec's two filler bytes, alternating, for whatever space is left.
	for (let i = 0; codewords.length < capacity; i++) codewords.push(i % 2 === 0 ? 0xec : 0x11);
	return codewords;
}

/**
 * Split into blocks, compute each block's ECC, then interleave both.
 *
 * Interleaving is the point of the block structure: a scuff on the code takes a
 * couple of codewords out of every block rather than wiping out one block
 * entirely, and each block can then repair itself.
 */
function interleave(data, version) {
	const [, eccPerBlock, blockCount] = VERSIONS[version];
	const shortLength = Math.floor(data.length / blockCount);
	const longBlocks = data.length % blockCount;
	const generator = rsGenerator(eccPerBlock);

	const dataBlocks = [];
	const eccBlocks = [];
	for (let i = 0, at = 0; i < blockCount; i++) {
		const length = shortLength + (i >= blockCount - longBlocks ? 1 : 0);
		const block = data.slice(at, at + length);
		at += length;
		dataBlocks.push(block);
		eccBlocks.push(rsRemainder(block, generator));
	}

	const out = [];
	for (let i = 0; i < shortLength + 1; i++) {
		for (const block of dataBlocks) if (i < block.length) out.push(block[i]);
	}
	for (let i = 0; i < eccPerBlock; i++) for (const block of eccBlocks) out.push(block[i]);
	return out;
}

// --- The matrix ---------------------------------------------------------------

function newMatrix(version) {
	const size = version * 4 + 17;
	return {
		size,
		// Function patterns and format areas: everything the data routes around.
		modules: new Array(size * size).fill(false),
		reserved: new Array(size * size).fill(false),
	};
}

function set(m, x, y, dark, reserve = true) {
	m.modules[y * m.size + x] = dark;
	if (reserve) m.reserved[y * m.size + x] = true;
}
const get = (m, x, y) => m.modules[y * m.size + x];
const isReserved = (m, x, y) => m.reserved[y * m.size + x];

function drawFunctionPatterns(m, version) {
	const size = m.size;

	// The three finders, each with its separator: an 8x8 block whose outer row and
	// column are light, so drawing the whole thing covers both at once.
	for (const [ox, oy] of [
		[0, 0],
		[size - 7, 0],
		[0, size - 7],
	]) {
		for (let dy = -1; dy <= 7; dy++) {
			for (let dx = -1; dx <= 7; dx++) {
				const x = ox + dx;
				const y = oy + dy;
				if (x < 0 || x >= size || y < 0 || y >= size) continue;
				const ring = Math.max(Math.abs(dx - 3), Math.abs(dy - 3));
				set(m, x, y, ring !== 2 && ring <= 3);
			}
		}
	}

	// Timing patterns: alternating modules bridging the finders, dark on even.
	for (let i = 8; i < size - 8; i++) {
		set(m, i, 6, i % 2 === 0);
		set(m, 6, i, i % 2 === 0);
	}

	// Alignment patterns, 5x5, at every pairing of the version's centres, minus the
	// three that would land on a finder.
	const centres = ALIGNMENT[version];
	for (const cx of centres) {
		for (const cy of centres) {
			const onFinder =
				(cx === 6 && cy === 6) || (cx === 6 && cy === size - 7) || (cx === size - 7 && cy === 6);
			if (onFinder) continue;
			for (let dy = -2; dy <= 2; dy++) {
				for (let dx = -2; dx <= 2; dx++) {
					set(m, cx + dx, cy + dy, Math.max(Math.abs(dx), Math.abs(dy)) !== 1);
				}
			}
		}
	}

	// The one module that is always dark, for no reason beyond the spec saying so.
	set(m, 8, size - 8, true);

	// Reserve the format information. Its values arrive after masking, since the
	// mask number is part of what they encode.
	for (let i = 0; i <= 8; i++) {
		if (i !== 6) set(m, 8, i, false);
		if (i !== 6) set(m, i, 8, false);
	}
	for (let i = 0; i < 8; i++) set(m, size - 1 - i, 8, false);
	for (let i = size - 7; i < size; i++) set(m, 8, i, false);
}

/** Walk the two-module-wide columns, bottom-right to top-left, laying down bits. */
function placeData(m, codewords) {
	const size = m.size;
	const total = codewords.length * 8;
	let bit = 0;
	let upward = true;

	for (let right = size - 1; right >= 1; right -= 2) {
		// Column 6 is the vertical timing pattern; the pairing skips over it.
		if (right === 6) right = 5;
		for (let vert = 0; vert < size; vert++) {
			for (let j = 0; j < 2; j++) {
				const x = right - j;
				const y = upward ? size - 1 - vert : vert;
				if (isReserved(m, x, y)) continue;
				// Past the end of the data are the remainder bits, which stay light.
				const dark = bit < total && ((codewords[bit >>> 3] >>> (7 - (bit & 7))) & 1) === 1;
				set(m, x, y, dark, false);
				bit++;
			}
		}
		upward = !upward;
	}
}

const MASKS = [
	(x, y) => (x + y) % 2 === 0,
	(_x, y) => y % 2 === 0,
	(x) => x % 3 === 0,
	(x, y) => (x + y) % 3 === 0,
	(x, y) => (Math.floor(y / 2) + Math.floor(x / 3)) % 2 === 0,
	(x, y) => ((x * y) % 2) + ((x * y) % 3) === 0,
	(x, y) => (((x * y) % 2) + ((x * y) % 3)) % 2 === 0,
	(x, y) => (((x + y) % 2) + ((x * y) % 3)) % 2 === 0,
];

function applyMask(m, mask) {
	const rule = MASKS[mask];
	for (let y = 0; y < m.size; y++) {
		for (let x = 0; x < m.size; x++) {
			if (isReserved(m, x, y)) continue;
			if (rule(x, y)) m.modules[y * m.size + x] = !m.modules[y * m.size + x];
		}
	}
}

/**
 * The spec's four penalty rules, summed. Lowest score picks the mask.
 *
 * They exist to keep a masked symbol from looking like its own function patterns,
 * or from drifting into large flat areas a scanner cannot lock onto.
 */
function penalty(m) {
	const size = m.size;
	let score = 0;

	// Rule 1: runs of five or more like modules, in either direction.
	for (let i = 0; i < size; i++) {
		for (const horizontal of [true, false]) {
			let run = 1;
			let previous = horizontal ? get(m, 0, i) : get(m, i, 0);
			for (let j = 1; j < size; j++) {
				const value = horizontal ? get(m, j, i) : get(m, i, j);
				if (value === previous) {
					run++;
				} else {
					if (run >= 5) score += run - 2;
					previous = value;
					run = 1;
				}
			}
			if (run >= 5) score += run - 2;
		}
	}

	// Rule 2: every 2x2 block of one colour.
	for (let y = 0; y < size - 1; y++) {
		for (let x = 0; x < size - 1; x++) {
			const v = get(m, x, y);
			if (v === get(m, x + 1, y) && v === get(m, x, y + 1) && v === get(m, x + 1, y + 1)) {
				score += 3;
			}
		}
	}

	// Rule 3: the finder-like 1:1:3:1:1 sequence with four light modules beside it.
	const a = [true, false, true, true, true, false, true, false, false, false, false];
	const b = [false, false, false, false, true, false, true, true, true, false, true];
	const matches = (read, at, pattern) => {
		for (let k = 0; k < 11; k++) if (read(at + k) !== pattern[k]) return false;
		return true;
	};
	for (let i = 0; i < size; i++) {
		for (let j = 0; j + 11 <= size; j++) {
			const row = (k) => get(m, k, i);
			const col = (k) => get(m, i, k);
			if (matches(row, j, a) || matches(row, j, b)) score += 40;
			if (matches(col, j, a) || matches(col, j, b)) score += 40;
		}
	}

	// Rule 4: how far the dark/light balance strays from even, in 5% steps.
	let dark = 0;
	for (const module of m.modules) if (module) dark++;
	score += Math.floor(Math.abs((dark * 100) / (size * size) - 50) / 5) * 10;

	return score;
}

/** The 15-bit format information: 5 data bits, a BCH(15,5) remainder, and a mask. */
function formatBits(mask) {
	const data = (ECC_LEVEL_M << 3) | mask;
	let remainder = data;
	for (let i = 0; i < 10; i++) remainder = (remainder << 1) ^ ((remainder >>> 9) * 0x537);
	return (((data << 10) | remainder) ^ 0x5412) & 0x7fff;
}

function drawFormat(m, mask) {
	const bits = formatBits(mask);
	const size = m.size;
	const bit = (i) => ((bits >>> i) & 1) === 1;

	// Copy one, wrapped around the top-left finder.
	for (let i = 0; i <= 5; i++) set(m, 8, i, bit(i));
	set(m, 8, 7, bit(6));
	set(m, 8, 8, bit(7));
	set(m, 7, 8, bit(8));
	for (let i = 9; i <= 14; i++) set(m, 14 - i, 8, bit(i));

	// Copy two, split between the other two finders, so a symbol with one corner
	// destroyed can still be read.
	for (let i = 0; i <= 7; i++) set(m, size - 1 - i, 8, bit(i));
	for (let i = 8; i <= 14; i++) set(m, 8, size - 15 + i, bit(i));
	set(m, 8, size - 8, true); // the always-dark module, back where it belongs
}

/** Encode `text`. Throws if it does not fit in version 6 (106 bytes at level M). */
function encodeQr(text) {
	const bytes = new TextEncoder().encode(text);
	const version = pickVersion(bytes.length);
	if (version === 0) throw new RangeError(`qr: ${bytes.length} bytes is past the 106-byte limit`);

	const codewords = interleave(dataCodewords(bytes, version), version);

	// The mask is chosen by building the symbol all eight ways and scoring each.
	let best = null;
	let bestScore = Infinity;
	for (let mask = 0; mask < 8; mask++) {
		const m = newMatrix(version);
		drawFunctionPatterns(m, version);
		placeData(m, codewords);
		applyMask(m, mask);
		drawFormat(m, mask);
		const score = penalty(m);
		if (score < bestScore) {
			bestScore = score;
			best = m;
		}
	}
	return { version, size: best.size, modules: best.modules };
}

/**
 * The symbol as a self-contained SVG.
 *
 * It carries its own white ground rather than inheriting one: a QR code needs dark
 * modules on a light field and a light quiet zone around them, and this file is
 * dropped into a page whose every other surface is near-black. Baking the contrast
 * in means the image is correct wherever it is placed, including a phone that
 * saves it out of the page to show someone later.
 *
 * One path for all the dark modules rather than a rect each: fewer nodes for
 * something that never animates.
 */
function toSvg(qr, quiet = 4) {
	const extent = qr.size + quiet * 2;
	const parts = [];
	for (let y = 0; y < qr.size; y++) {
		for (let x = 0; x < qr.size; x++) {
			if (qr.modules[y * qr.size + x]) parts.push(`M${x + quiet} ${y + quiet}h1v1h-1z`);
		}
	}
	return (
		`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${extent} ${extent}" ` +
		`width="${extent * 8}" height="${extent * 8}" shape-rendering="crispEdges" ` +
		`role="img" aria-label="${URL_TO_ENCODE}">` +
		`<title>${URL_TO_ENCODE}</title>` +
		`<rect width="${extent}" height="${extent}" fill="#ffffff"/>` +
		`<path fill="#0b0f14" d="${parts.join("")}"/>` +
		`</svg>\n`
	);
}

const qr = encodeQr(URL_TO_ENCODE);
const out = join(dirname(dirname(fileURLToPath(import.meta.url))), "public", "qr-fieldmaps.svg");
await writeFile(out, toSvg(qr));
console.log(`${URL_TO_ENCODE} -> version ${qr.version}, ${qr.size}x${qr.size} modules`);
console.log(`wrote ${out}`);
