import type { ControlPoint } from "./transform.js";
import {
	labelPointsOfInterest,
	type LabeledPointOfInterest,
	type PointOfInterest,
} from "./points-of-interest.js";
import {
	SCENARIOS,
	type BoundaryLine,
	type Headquarters,
	type LatLng,
	type Scenario,
	type Zone,
} from "./scenarios/index.js";
import type { OsmThemeName } from "./osm-map.js";
import { compareBySchedule, type EventSchedule } from "./event-schedule.js";

// =============================================================================
//  Scenarios live in src/scenarios/ (labels + play area) and points of interest
//  in src/points-of-interest.ts (shared coordinates). This file only wires the
//  shared OSM base + the legacy photo maps into selectable maps, plus a couple of
//  tuning constants at the bottom.
// =============================================================================

export type { PointOfInterest, LabeledPointOfInterest };

/** One selectable map: a photo overlay OR an OSM vector scenario. */
export interface MapDefinition {
	/** Stable identifier used for persistence and URLs. */
	id: string;
	/** Label shown in the map selector dropdown. */
	name: string;
	/** One-line description for the landing page card. */
	blurb?: string;
	/** The English version of `blurb`, shown to a non-German browser. */
	blurbEn?: string;
	/** When the event runs; drives the landing card's date and the overview ordering. */
	schedule?: EventSchedule;
	/** Accent colour for the landing card. */
	accent?: string;
	/** Path to a photo map image (drop the file in /public). Omit for OSM maps. */
	image?: string;
	/** Path to the bundled OSM GeoJSON to render as a vector map. Omit for photos. */
	vectorData?: string;
	/** Which OSM look to render (vector maps only). Defaults to "opt". */
	theme?: OsmThemeName;
	/** Pixel dimensions of the coordinate canvas (image size, or OSM canvas size). */
	width: number;
	height: number;
	/** Hardcoded control points tying GPS to image/canvas pixels. */
	controlPoints: ControlPoint[];
	/** PoI id -> label to show on this map. Only listed ids are shown. */
	poiNames: Record<string, string>;
	/**
	 * Active play-area boundary as [lat, lng] points. Everything outside is covered
	 * by the out-of-bounds texture. Empty/undefined = whole field, no mask.
	 */
	playArea?: LatLng[];
	/** Marked areas traced from the event's tactical map. */
	zones?: Zone[];
	/** Faction headquarters with their emblems. */
	headquarters?: Headquarters[];
	/** Open frontlines traced from the event's tactical map. */
	lines?: BoundaryLine[];
}

// Shared calibration for the OSM vector base. Every OSM scenario renders on this
// exact canvas, generated by scripts/fetch-osm.mjs (which also prints these numbers).
const OSM_BASE = {
	vectorData: "map_osm.geojson",
	width: 2106,
	height: 1058,
	controlPoints: [
		{ lat: 52.3855, lng: 11.809, px: 0, py: 0 }, // TL
		{ lat: 52.3855, lng: 11.84, px: 2106, py: 0 }, // TR
		{ lat: 52.376, lng: 11.809, px: 0, py: 1058 }, // BL
		{ lat: 52.376, lng: 11.84, px: 2106, py: 1058 }, // BR
	] satisfies ControlPoint[],
};

/** Turn a scenario into a selectable map by resolving its base. */
function scenarioToMap(scenario: Scenario): MapDefinition {
	const common = {
		id: scenario.id,
		name: scenario.name,
		blurb: scenario.blurb,
		blurbEn: scenario.blurbEn,
		schedule: scenario.schedule,
		accent: scenario.accent,
		poiNames: scenario.poiNames,
		playArea: scenario.playArea,
		zones: scenario.zones,
		headquarters: scenario.headquarters,
		lines: scenario.lines,
	};
	if (scenario.base.kind === "osm") {
		return { ...common, ...OSM_BASE, theme: scenario.base.theme ?? "opt" };
	}
	const { image, width, height, controlPoints } = scenario.base;
	return { ...common, image, width, height, controlPoints };
}

/** All selectable maps, one per scenario, in registration order. */
export const MAPS: MapDefinition[] = SCENARIOS.map(scenarioToMap);

/**
 * The maps in the order a player wants them: the event that is running right now
 * first, then the next one, and so on — style variants (no schedule) last.
 *
 * A function rather than a constant because the answer depends on today's date, and
 * this is a PWA that people leave open for a whole weekend. Cheap enough to call per
 * render; the list is single digits long.
 */
export function mapsByDate(now = new Date()): MapDefinition[] {
	return [...MAPS].sort((a, b) => compareBySchedule(a, b, now));
}

/** Which map loads on first visit (before any saved preference or URL). */
export const DEFAULT_MAP_ID = MAPS[0]?.id ?? "";

export function getMapById(id: string): MapDefinition {
	return MAPS.find((map) => map.id === id) ?? MAPS[0];
}

/** PoIs visible on a map: shared coordinates with that map's scenario labels. */
export function getPointsOfInterestForMap(mapId: string): LabeledPointOfInterest[] {
	return labelPointsOfInterest(getMapById(mapId).poiNames);
}

/**
 * Position smoothing: how much of each new fix is taken on board, in
 * `smoothed += k * (raw - smoothed)`. So **1 = raw GPS (jumpy), 0 = frozen** at the
 * first fix — lower means *more* smoothing, not less. ~0.4 is a good start.
 */
export const POSITION_SMOOTHING = 0.4;
/** If a new fix jumps more than this many meters, snap instead of smoothing. */
export const SNAP_DISTANCE_M = 25;

/** Heading smoothing for the compass (low-pass on the angle). Same scale as above:
 *  1 = raw magnetometer, 0 = frozen. */
export const HEADING_SMOOTHING = 0.25;
/** Above this ground speed (m/s) prefer GPS course over the (metal-noisy) compass. */
export const GPS_HEADING_SPEED = 0.7;
