import type { ControlPoint } from "./transform.js";
import {
	labelPointsOfInterest,
	type LabeledPointOfInterest,
	type PointOfInterest,
} from "./points-of-interest.js";
import { SCENARIOS, type LatLng, type Scenario } from "./scenarios/index.js";

// =============================================================================
//  Scenarios live in src/scenarios/ (labels + play area) and points of interest
//  in src/points-of-interest.ts (shared coordinates). This file only wires the
//  shared OSM base + the legacy photo maps into selectable maps, plus a couple of
//  tuning constants at the bottom.
// =============================================================================

export type { PointOfInterest, LabeledPointOfInterest };

/** One selectable map: a photo overlay OR an OSM vector scenario. */
export interface MapDefinition {
	/** Stable identifier used for persistence and URLs. */
	id: string;
	/** Label shown in the map selector dropdown. */
	name: string;
	/** Path to a photo map image (drop the file in /public). Omit for OSM maps. */
	image?: string;
	/** Path to the bundled OSM GeoJSON to render as a vector map. Omit for photos. */
	vectorData?: string;
	/** Pixel dimensions of the coordinate canvas (image size, or OSM canvas size). */
	width: number;
	height: number;
	/** Hardcoded control points tying GPS to image/canvas pixels. */
	controlPoints: ControlPoint[];
	/** PoI id -> label to show on this map. Only listed ids are shown. */
	poiNames: Record<string, string>;
	/**
	 * Active play-area boundary as [lat, lng] points. Everything outside is covered
	 * by the out-of-bounds texture. Empty/undefined = whole field, no mask.
	 */
	playArea?: LatLng[];
}

// Shared calibration for the OSM vector base. Every scenario renders on this exact
// canvas, generated by scripts/fetch-osm.mjs (which also prints these numbers).
const OSM_BASE = {
	vectorData: "map_osm.geojson",
	width: 2106,
	height: 1058,
	controlPoints: [
		{ lat: 52.3855, lng: 11.809, px: 0, py: 0 }, // TL
		{ lat: 52.3855, lng: 11.84, px: 2106, py: 0 }, // TR
		{ lat: 52.376, lng: 11.809, px: 0, py: 1058 }, // BL
		{ lat: 52.376, lng: 11.84, px: 2106, py: 1058 }, // BR
	] satisfies ControlPoint[],
};

/** Turn a scenario (labels + play area) into a selectable OSM vector map. */
function scenarioToMap(scenario: Scenario): MapDefinition {
	return {
		id: `osm-${scenario.id}`,
		name: scenario.name,
		...OSM_BASE,
		poiNames: scenario.poiNames,
		playArea: scenario.playArea,
	};
}

const scenarioById = (id: string) => SCENARIOS.find((s) => s.id === id);

/**
 * All selectable maps: one OSM vector map per scenario (primary), then the legacy
 * hand-made photo maps (the originals; their out-of-bounds cover is baked into the
 * image, so they need no play-area mask). Photo maps borrow their scenario's labels.
 */
export const MAPS: MapDefinition[] = [
	...SCENARIOS.map(scenarioToMap),
	{
		id: "m24",
		name: "Mission24 (Foto)",
		image: "map_m24.png",
		width: 1598,
		height: 906,
		controlPoints: [
			{ lat: 52.382855, lng: 11.821238, px: 561, py: 301 }, // Lima
			{ lat: 52.382526, lng: 11.827816, px: 893, py: 328 }, // Bravo
			{ lat: 52.381769, lng: 11.833687, px: 1193, py: 390 }, // Echo
			{ lat: 52.379209, lng: 11.827408, px: 874, py: 603 }, // Sierra
		],
		poiNames: scenarioById("m24")?.poiNames ?? {},
	},
	{
		id: "opt",
		name: "Op Tschernobyl (Foto)",
		image: "map_opt.jpg",
		width: 2048,
		height: 1448,
		controlPoints: [
			{ lat: 52.382855, lng: 11.821238, px: 786, py: 703 }, // Lima
			{ lat: 52.382516, lng: 11.827811, px: 1359, py: 752 }, // Bravo
			{ lat: 52.379208, lng: 11.827409, px: 1323, py: 1227 }, // Sierra
		],
		poiNames: scenarioById("opt")?.poiNames ?? {},
	},
];

/** Which map loads on first visit (before any saved preference). */
export const DEFAULT_MAP_ID = MAPS[0]?.id ?? "";

export function getMapById(id: string): MapDefinition {
	return MAPS.find((map) => map.id === id) ?? MAPS[0];
}

/** PoIs visible on a map: shared coordinates with that map's scenario labels. */
export function getPointsOfInterestForMap(mapId: string): LabeledPointOfInterest[] {
	return labelPointsOfInterest(getMapById(mapId).poiNames);
}

/** Position smoothing: 0 = raw GPS (jumpy), 1 = frozen. ~0.4 is a good start. */
export const POSITION_SMOOTHING = 0.4;
/** If a new fix jumps more than this many meters, snap instead of smoothing. */
export const SNAP_DISTANCE_M = 25;

/** Heading smoothing for the compass (low-pass on the angle). */
export const HEADING_SMOOTHING = 0.25;
/** Above this ground speed (m/s) prefer GPS course over the (metal-noisy) compass. */
export const GPS_HEADING_SPEED = 0.7;
